### ISSUE TITLE
Issues when uploading and starting prints

### ISSUE THREAD

**Issue by gothickitty93** [jneilliii/OctoPrint-BambuPrinter#15]
Hello,

I am experiencing issues when I try to upload .3mf files, as well as start the print. When I first upload the file, OctoPrint says it successfully streamed the file over, but it doesn't actually show up in the SD card list, even after a refresh. Then, when I go to print the file, it starts and then immediately fails.
[octoprint-logs (1).zip](https://github.com/jneilliii/OctoPrint-BambuPrinter/files/14590389/octoprint-logs.1.zip)

**Comment by gothickitty93** [comment]
Oh, my printer is an A1 mini

**Comment by gothickitty93** [comment]
I should also mention that I can't seem to access the FTP server as mentioned here [https://forum.bambulab.com/t/we-can-now-connect-to-ftp-on-the-p1-and-a1-series/](url)

**Comment by gothickitty93** [comment]
Heh. Now every time I try to connect, I'm getting timeout errors. Tried rebooting the printer and OctoPrint

```
Changing monitoring state from "Offline" to "Detecting serial connection"
Performing autodetection with 7 port/baudrate candidates: BAMBU@115200, BAMBU@250000, BAMBU@230400, BAMBU@57600, BAMBU@38400, BAMBU@19200, BAMBU@9600
Trying port BAMBU, baudrate 115200
Handshake attempt #1 with timeout 2.0s
Connected to: BAMBU(read_timeout=2.0,write_timeout=10.0,options={'device_type': 'A1MINI', 'host': '192.168.0.75'}), starting monitor
Send: N0 M110 N0*125
Recv: ok
Changing monitoring state from "Detecting serial connection" to "Operational"
Send: N0 M110 N0*125
Recv: ok
Recv: ok
Send: N1 M115*39
Recv: Bambu Printer Integration
Recv: Cap:EXTENDED_M20:1
Recv: Cap:LFN_WRITE:1
Recv: Cap:LFN_WRITE:1
Recv: ok
Send: N2 M21*18
Recv: SD card ok
Recv: ok
Send: m501
Send: m420 s1
Send: N3 M20 L T*10
Recv: Begin file list
Communication timeout while idle, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
Send: N4 M20 L T*13
Communication timeout while idle, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
Send: N5 M105*34
No response from printer after 3 consecutive communication timeouts, considering it dead. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
Changing monitoring state from "Operational" to "Offline after error"
Connection closed, closing down monitor
```

**Comment by gothickitty93** [comment]
Ok, it seems that the list files command is timing out on the printer either after it has been on for a little bit, or after multiple attempts to connect to it's FTP server

**Comment by gothickitty93** [comment]
[octoprint-logs.zip](https://github.com/jneilliii/OctoPrint-BambuPrinter/files/14593766/octoprint-logs.zip)
More logs

**Comment by gothickitty93** [comment]
I think some of the issues may be my own, too. I had a tiny 128MB SD card in it, and it complained that it was full already, which is weird because I only have one file on it. I have been at work all day, so my notes were all remote access. I’ll experiment more in the next few days

**Comment by jneilliii** [comment]
please give the latest release 0.0.18 and report back if this process is working any better for you now.

**Comment by gothickitty93** [comment]
I was able to upload a file to the SD and start the print directly from OctoPrint successfully. (BTW changed SD card to a much larger size, that seems to have helped too)
