### ISSUE TITLE
cant Use cloud connection

### ISSUE THREAD

**Issue by hashoom8** [jneilliii/OctoPrint-BambuPrinter#21]
![Screenshot 2024-04-22 081327](https://github.com/jneilliii/OctoPrint-BambuPrinter/assets/46507374/79515dea-c112-4c11-9a33-fc41f30498e2)

i know my email but not the password , because i always use google sign in

how can i found my Auth Token

**Comment by jneilliii** [comment]
That's a good question. I'll have to look into the underlying python module I'm using for this plugin integration and see if they account for that in any way.

**Comment by jneilliii** [comment]
Looks like you can add a password to your account. See the method described [here](https://github.com/greghesp/ha-bambulab#setup-using-bambu-cloud-w-oauth)
