### ISSUE TITLE
The current print isn't being recognized by this plugin when I try to use the 'print again' function

### ISSUE THREAD

**Issue by JanUmbach** [jneilliii/OctoPrint-BambuPrinter#25]
My environment:
Printer: A1
OctoPrint-BambuPrinter Plugin is running localy, but Slicer will send data over the cloud.

When I start a print from my Bambu Studio Slicer, everything works fine.

When I start a print from the display, it also works fine. But after a print is finished, I have the option to click "Print Again" at the A1 display, and now he adds a 'cache/' prefix to the filename instruction. The plugin is searching for the filename e.g. 'cache/myFile.3mf', but it won't find it.

Terminal says: `Recv: cache/testt.3mf open failed`
[octoprint.log](https://github.com/jneilliii/OctoPrint-BambuPrinter/files/15287230/octoprint.log)

**Comment by jneilliii** [comment]
I think I may have fixed the issue in the above commit. Could you please test on your end by installing the plugin using the URL below in Plugin Manager > Get More > ...from URL and report back?

```
https://github.com/jneilliii/OctoPrint-BambuPrinter/archive/refs/heads/bugfix/print_again_cache.zip
```

**Comment by JanUmbach** [comment]
Yes that fixes that issue, thanks :)
