### ISSUE TITLE
Unable to connect to P1P

### ISSUE THREAD

**Issue by navytrav** [jneilliii/OctoPrint-BambuPrinter#26]
I dug out and set up an older raspi to give this a try, but it will not connect. I may be missing something, and any help getting it working would be appreciated.

Fresh install of OctoPi on Raspberry Zero 2 W.
P1P in cloud mode.
No errors in plugin console log.
Clicking login on the configuration page does not visibly do anything except remove the entered auth token.
"pybambu - WARNING - On Disconnect: Disconnected from Broker: 5" showing in Octoprint log every few seconds.
"pybambu -ERROR - P1P: Socket error: EOF occurred in violation of protocol (_ssl.c:1123)
octoprint.server.api - ERROR - Error while executing SimpleApiPlugin bambu_printer
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/server/api/__init__.py", line 162, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_bambu_printer/__init__.py", line 56, in on_api_command
    bambu_cloud.login(data["region"], data["email"], data["password"])
  File "/home/pi/oprint/lib/python3.9/site-packages/pybambu/bambu_cloud.py", line 99, in login
    self._username = self._get_username_from_authentication_token()
  File "/home/pi/oprint/lib/python3.9/site-packages/pybambu/bambu_cloud.py", line 36, in _get_username_from_authentication_token
    b64_string = self._auth_token.split(".")[1]
IndexError: list index out of range"
No logs are created after enabling info level logging on all octoprint.plugins.bambu_printer options.

**Comment by jneilliii** [comment]
Logging needs to be set to debug to get anything in octoprint.log from the plugin. I would recommend trying not in cloud mode to begin with. The printer should still allow for connecting locally outside of the cloud connection and just needs the IP address of your printer and the access code. I do not know where in the printer menu that information exists since I don't have a P1P, but it should be in there somewhere.

**Comment by navytrav** [comment]
I think I may have figured it out. I was able to connect, but it disconnected fairly quickly. Its mid long print, so I can't fully test.

Basic problem is I didn't double check the access code, just thought the picture I had from before was still accurate.

**Comment by jneilliii** [comment]
Just checking in to see if you are still having connection issues or not before closing?

**Comment by navytrav** [comment]
Issue caused by my own mistake
