### ISSUE TITLE
Timelapse files on P1P/P1S

### ISSUE THREAD

**Issue by ulmeck** [jneilliii/OctoPrint-BambuPrinter#29]
Looks like on the  0.21 version the plugin is looking for *mp4 files for the timelapses. On the P1P/P1S (maybe A1?) they're stored as .avi files using the same path. Thumbnails are still .jpg, though.

**Comment by jneilliii** [comment]
Thank you for this information. as mentioned on the release notes only tested on the X1C. I can make that adjustment to the code to also look for avi files.

**Comment by jneilliii** [comment]
added support of avi file listings with version 0.0.22.
