### ISSUE TITLE
A1 Mini pausing print does nothing octo print reports pausing status

### ISSUE THREAD

**Issue by Kitki30** [jneilliii/OctoPrint-BambuPrinter#36]
I tried to use pinozcam plugin to prevent failed prints but when it started to pause the print it never paaused but octo reported pausing status

**Comment by Kitki30** [comment]
i found out that you need to set pausing command to
M400 U1

**Comment by Kitki30** [comment]
but fans are 100%

**Comment by jneilliii** [comment]
You should be able to add the commands to turn off fans on pause in OctoPrint's gcode scripts section. Probably want to make sure to turn them back on in resume.

**Comment by jneilliii** [comment]
Was your pause command set as M25 before? The plugin intercepts that command and actually seems the pause mqtt command to the printer.

**Comment by Kitki30** [comment]
idk, it was set to something default.

**Comment by Kitki30** [comment]
M25 is set to sd cancel command

**Comment by Kitki30** [comment]
![xd](https://github.com/user-attachments/assets/d776434c-686e-47f0-9981-cad2e0a4a4e9)

**Comment by jneilliii** [comment]
Yeah, so unless your printing files uploaded to OctoPrint directly into local storage this shouldn't effect how the plugin works. The plugin acts as virtual sd card to OctoPrint and the files that are printed should be seen as sd card files as indicated by the little icon in the upper right of the file.

**Comment by Kitki30** [comment]
It was set to default: three commands m25 was the last

pt., 2 sie 2024, 23:08 użytkownik jneilliii ***@***.***>
napisał:

**Comment by Kitki30** [comment]
It was set to default: three commands m25 was the last

**Comment by Kitki30** [comment]
changed it to only m25

**Comment by Kitki30** [comment]
i cant see if its working im in my grandpa's home now
maybe i can see test it tomorrow

i mainly send prints through bambu studio, i use octoprint to see print progress from my wear os watch with octoapp but i see that octoprint have some cool plugins that makes printing better i host it on 8gb pi 5

**Comment by Kitki30** [comment]
idk if its plugin problem or octoapp problem but if its possible can you fix that when i hit start printing button on octo app it shows me only files stored on rapsberry pi's sd card not printer sd card maybe its virtual sd card issue

**Comment by Kitki30** [comment]
also can you fix that when the printer is not even turned on octo print thinks its operational (when you press connect button)
![image](https://github.com/user-attachments/assets/76083362-2a32-4f32-a133-e231add7bc47)

**Comment by Kitki30** [comment]
the internet quality is poor here so i can reply late

**Comment by jneilliii** [comment]
> idk if its plugin problem or octoapp problem but if its possible can you fix that when i hit start printing button on octo app it shows me only files stored on rapsberry pi's sd card not printer sd card maybe its virtual sd card issue

I have no idea how to filter OctoApp list of files, @crysxd may be able to tell us though.

**Comment by jneilliii** [comment]
> also can you fix that when the printer is not even turned on octo print thinks its operational (when you press connect button) ![image](https://private-user-images.githubusercontent.com/84147906/354822049-76083362-2a32-4f32-a133-e231add7bc47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MDI5MzUsIm5iZiI6MTcyMjcwMjYzNSwicGF0aCI6Ii84NDE0NzkwNi8zNTQ4MjIwNDktNzYwODMzNjItMmEzMi00ZjMyLWExMzMtZTIzMWFkZDdiYzQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDE2MzAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyODJhYTQyNDA3MzI4ZTMwMWE1MzI2YzA5MjQ0MTczMzkwNDU2OGQ5NDcxZDYxMTEyZDhhY2ZhODhjNzBmMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c3vw8mCD5oALIh-h8_MjywcZAtgHjr0fu-2whzdK28o)

I will have to test this one out, prior to the recent refactor by @Valemos OctoPrint state would disconnect when the printer was powered off.

**Comment by Kitki30** [comment]
ok

**Comment by crysxd** [comment]
> > idk if its plugin problem or octoapp problem but if its possible can you fix that when i hit start printing button on octo app it shows me only files stored on rapsberry pi's sd card not printer sd card maybe its virtual sd card issue
> 
> I have no idea how to filter OctoApp list of files, @crysxd may be able to tell us though.

OctoApp doesn't support files from the printers and card. It's that simple 😅 

I never implemented it and it's not frequently requested

**Comment by Kitki30** [comment]
> > > idk if its plugin problem or octoapp problem but if its possible can you fix that when i hit start printing button on octo app it shows me only files stored on rapsberry pi's sd card not printer sd card maybe its virtual sd card issue
> > 
> > 
> > I have no idea how to filter OctoApp list of files, @crysxd may be able to tell us though.
> 
> OctoApp doesn't support files from the printers SD card. It's that simple 😅
> 
> I never implemented it and it's not frequently requested

OK Thanks for reply!

**Comment by Kitki30** [comment]
> > > > idk if its plugin problem or octoapp problem but if its possible can you fix that when i hit start printing button on octo app it shows me only files stored on rapsberry pi's sd card not printer sd card maybe its virtual sd card issue
> > > 
> > > 
> > > I have no idea how to filter OctoApp list of files, @crysxd may be able to tell us though.
> > 
> > 
> > OctoApp doesn't support files from the printers SD card. It's that simple 😅
> > I never implemented it and it's not frequently requested
> 
> OK Thanks for reply!

Does octoapp have wear os notifications or my watch is broken? I have octo companion plugin

**Comment by crysxd** [comment]
That's not the place to discuss this, but notifications from the phone also show on the watch

**Comment by Kitki30** [comment]
> That's not the place to discuss this, but notifications from the phone also show on the watch

ok
