### ISSUE TITLE
[FR]: Any way to get Spoolman usage tracking working?

### ISSUE THREAD

**Issue by dohlin** [jneilliii/OctoPrint-BambuPrinter#51]
This is probably a stupid question/request given the 'openness' (lack-thereof) of these printers, but I figure it doesn't hurt to just confirm.  I've installed the plugin in Octoprint, but tracking seems to be non-functional.  There's no way to get Spoolman filament usage tracking working with this plugin setup, correct?

**Comment by jneilliii** [comment]
My assumption is that this data isn't available to spool man because the files are printed from virtual SD card and OctoPrint doesn't have the metadata associated with those types of files.
