### ISSUE TITLE
[BUG]: Access code required when connecting to Bambu Cloud

### ISSUE THREAD

**Issue by Nicolas-Chasteler** [jneilliii/OctoPrint-BambuPrinter#57]
**Describe the Bug**
Version 0.1.8rc3
Connecting to printer using Bambu Cloud requires a value in the access code field. The virtual printer doesn't initialize and a connection can't be made and a "No serial port found" error is displayed. 

This can be fixed by adding any value in the access code field.

**Expected Behavior**
Access code is not required to be filled in to connect through the Bambu Cloud.

**Debug Logs**
N/A

**Screenshots**
No access code:
![image](https://github.com/user-attachments/assets/588fad80-51d9-441c-aee9-7a6928b838d7)
![image](https://github.com/user-attachments/assets/1bdb0715-b750-483e-ac0a-eb6853bede76)

Access code:
![image](https://github.com/user-attachments/assets/db7566b0-47cb-46dd-9286-825c36dc658b)
![image](https://github.com/user-attachments/assets/28cf3399-0cd2-40e3-9ebb-863629c0df67)

**Printer and Plugin Setting Details**

* Printer model? P1S
* Is your printer connected to Bambu Cloud? Yes
* Is the  plugin configured for local access only? No

**Comment by jneilliii** [comment]
I suspect this is just an internal issue with creating the bambu client connection. The module itself requires this as a parameter, but I will do some internal testing/code review to validate.

**Comment by jneilliii** [comment]
Ok, it didn't take me long to figure out that the access code is still required in order to pull file listings and access to timelapses from the printer via ftps. I don't think there's any other way to get that directly from the cloud mqtt connection, which is what temperature, print progress, etc. data comes from.
