### ISSUE TITLE
[FR]: More than one printer?

### ISSUE THREAD

**Issue by metawops** [jneilliii/OctoPrint-BambuPrinter#62]
**Is your feature request related to a problem? Please describe.**
I own two BambuLab printers, an A1 mini and an X1C and would love to be able to control both from within OctoPrint.

**Describe the solution you'd like**
Being able to add & configure more than one printer would be great.

**Describe alternatives you've considered**
<none>

**Additional context**
<none>

**Comment by jneilliii** [comment]
OctoPrint doesn't support controlling multiple printers at a time, but you can run multiple instances of OctoPrint to control one each instance. I'd suggest looking at the octoprint_deploy script for setting up a second instance.

**Comment by metawops** [comment]
Ah, I see. Thanks for the hint! 🙏
