### ISSUE TITLE
[BUG]: Small typo in the Bambu Print Options dialog

### ISSUE THREAD

**Issue by metawops** [jneilliii/OctoPrint-BambuPrinter#64]
<img width="584" alt="SCR-20241229-mcol" src="https://github.com/user-attachments/assets/89cf5aee-842c-49c4-b48f-cf909e868061" />

Also, the "here" link just scrolls the main page so that the AMS gets into view. However, no "usage details". 🤷‍♂️

**Comment by jneilliii** [comment]
Yeah, I haven't gotten around to explaining the AMS mapping stuff in a doc. Thanks for pointing out the typo.
